name: CPOBounty
version: '1.0-SNAPSHOT'
main: me.knovius.cpobounty.CPOBounty
api-version: '1.16'
softdepend: [PlaceholderAPI]
commands:
  bounty:
    description: admin command
  bountytop:
    description: displays bounty leaderboard